//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleTrackingGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeopleTrackingGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\background.txt.
        /// </summary>
        internal static string BackgroundDir {
            get {
                return ResourceManager.GetString("BackgroundDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete\bookshelf.png.
        /// </summary>
        internal static string BookShelfBitmapDir {
            get {
                return ResourceManager.GetString("BookShelfBitmapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete\box.png.
        /// </summary>
        internal static string BoxBitmapDir {
            get {
                return ResourceManager.GetString("BoxBitmapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete\cart.png.
        /// </summary>
        internal static string CartBitmapDir {
            get {
                return ResourceManager.GetString("CartBitmapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete\chair.png.
        /// </summary>
        internal static string ChairBitmapDir {
            get {
                return ResourceManager.GetString("ChairBitmapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kinect cable is connected..
        /// </summary>
        internal static string ConnectNotification {
            get {
                return ResourceManager.GetString("ConnectNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Record\canvasForground\.
        /// </summary>
        internal static string DirectionCanvasForground {
            get {
                return ResourceManager.GetString("DirectionCanvasForground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Record\.
        /// </summary>
        internal static string DirectoryErrorLog {
            get {
                return ResourceManager.GetString("DirectoryErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Record\Joint\.
        /// </summary>
        internal static string DirectoryJoint {
            get {
                return ResourceManager.GetString("DirectoryJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\PeopleTracking\Record\Position\.
        /// </summary>
        internal static string DirectoryPosition {
            get {
                return ResourceManager.GetString("DirectoryPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Restart.bat.
        /// </summary>
        internal static string DirectoryRestartBat {
            get {
                return ResourceManager.GetString("DirectoryRestartBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\PeopleTracking\Record\RFID\.
        /// </summary>
        internal static string DirectoryRFID {
            get {
                return ResourceManager.GetString("DirectoryRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kinect cable is disconnected..
        /// </summary>
        internal static string DisconnectError {
            get {
                return ResourceManager.GetString("DisconnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rutgerslab731@gmail.com.
        /// </summary>
        internal static string EmailFrom {
            get {
                return ResourceManager.GetString("EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rutgerslab731731.
        /// </summary>
        internal static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rutgerslab731@gmail.com.
        /// </summary>
        internal static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An reader connection error has occured..
        /// </summary>
        internal static string ReaderConnectionError {
            get {
                return ResourceManager.GetString("ReaderConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeedwayR-11-7E-55.local.
        /// </summary>
        internal static string ReaderHost {
            get {
                return ResourceManager.GetString("ReaderHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete\table.png.
        /// </summary>
        internal static string TableBitmapDir {
            get {
                return ResourceManager.GetString("TableBitmapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete_Irregular.
        /// </summary>
        internal static string TemplateIrregular {
            get {
                return ResourceManager.GetString("TemplateIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ActivityRecognition\Templete.
        /// </summary>
        internal static string TemplateRoot {
            get {
                return ResourceManager.GetString("TemplateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string TiltAngle {
            get {
                return ResourceManager.GetString("TiltAngle", resourceCulture);
            }
        }
    }
}
